路径: 姓名

在……之上:
推:
分支机构: [主要的]
workflow_dispatch:

工作:
建立:
连续的：Ubuntu-最新
    
步骤:
    - uses: 操作/结帐@v4
    
    - 姓名: 设置JDK17
uses: 操作/设置-Java@v4
和……一起:
java版: '17'
分布: 'temurin'
    
    - 姓名: 安装Android SDK
uses: android-actions/setup-android@v3
    
    - 姓名: 授予gradlew的执行权限
跑: chmod+x gradlew
    
    - 姓名: 生成调试安装包
跑: ./gradlew装配调试
    
    - 姓名: 上传安装包
uses: 操作/上载工件@v4
和……一起:
姓名: app-debug
路径: app/build/outputs/apk/debug/app-debug.apk
